global_planning:
  global_path_topic: '/move_base/global_path'
  min_wall_distance: 1
  goal: [0, 0]

local_planning:
  global_path_topic: '/move_base/global_path'
  goal_reached_threshold: 0.08
  cost_weights:
    x: 1.0
    y: 1.0
    theta: 0.001
    v: 0.1
    w: 0.001
  rate_hz: 5
  horizon_in_seconds: 2.0
  control_params:
    min_v: -0.2
    max_v: 0.2
    min_w: -10
    max_w: 10
    dv: 0.1
    dw: 0.5
    max_dv: 0.3
    max_dw: 15
  a: 4


